### ISSUE TITLE
Pose optimization

### ISSUE THREAD

**Issue by dengjuncan** [yenchenlin/iNeRF-public#4]
Hi, thanks for your code!
It seems that the pose optimization in this code is different from that in the paper of iNeRF?

**Comment by domef** [comment]
I noticed this too. I can't find the code of the paragraph 4.A in the repo.

**Comment by Egoago** [comment]
Implementing linear optimization on Lie groups with PyTorch is not so straightforward. There exist a library just for that reason https://github.com/princeton-vl/lietorch.
My guess would be, that the authors did not make the effort to implement it properly and just optimized in R^4x4 directly. It should be noted though that the code is for visualization purposes only.
Is this the case @yenchenlin ?

**Comment by yenchenlin** [comment]
Hi all,

The original implementation in Jax is implemented with Lie group optimization but I didn't port that part to PyTorch.

@Egoago 's hypothesis is incorrect and I can update the code to use [lietorch](https://github.com/princeton-vl/lietorch) later today.

**Comment by Egoago** [comment]
Thank you! It would be a great help to see the original algorithm in code.

**Comment by yenchenlin** [comment]
@Egoago 

The code for the exact method using exponential coordinates can be found at the following link. But note this code doesn’t actually run — it was used in conjunction with Google's internal tools that we couldn’t fully release easily. However, the code can be used as a reference. 
https://github.com/google-research/google-research/tree/master/inerf
