### ISSUE TITLE
Question about trained PixelNeRF used in iNeRF

### ISSUE THREAD

**Issue by mah-asd** [yenchenlin/iNeRF-public#8]
Hi, thank you for your excellent job, 
I'm pretty new here, and I have a question. 
Usually, each NeRF model saves the network as checkpoints (.ckpt) 
How come your trained model in "iNeRF/pixel-nerf/checkpoints/<name of the data> is some binary files? My goal here is to use other trained networks in checkpoint format.
Thanks in advance

**Comment by KJZhuAutomatic** [comment]
@mah-asd ,hi, i have same question, how you deal with it please. If it's possible like the train procedure in pixelnerf codebase.
